name: JoeyKarate.com
favicon: null
layout_spectrum: 0.9664943793322891
typography_spectrum: 0.7802095611114055
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#6f6f6f'
    - '#e1adbf'
    - '#b40000'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
